eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
employee:
 eid: 100
 name:
   first: Rishabh
   middle:
   last: Jain
   
environment: master (application-dev)
